services:
  backend:
    build:
      context: .  # Use project root as context
      dockerfile: backend/Dockerfile  # Path to Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=app
      - DB_PASSWORD=yourpassword
      - DB_NAME=appdb
      - SWAGGER_HOST=localhost:8081  # For correct swagger base URL
    depends_on:
      migrations:
        condition: service_completed_successfully
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: app
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: migrate/migrate
    volumes:
      - ./sql/migrations:/migrations
    command: ["-path=/migrations", "-database", "postgres://app:yourpassword@db:5432/appdb?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: